### ISSUE TITLE
minor error in library

### ISSUE THREAD

**Issue by PriestOfFerns** [kuleshov-group/llmtools#19]
Not sure if this is because i somehow installed an older version of the llmtune site package or something, but when trying to the run the llmtune command, i got a `could not find llmtune.engine.quant.algorithm.gpq` error. Going into the .egg site package and fixing a line in `/llmtune/engine/quant/algorithm/executor.py`, where gptq was misspelled (as well as adding a `import torch` line) fixed the issue.

**Comment by PriestOfFerns** [comment]
Sorry if the details are a bit fuzzy, i did all that yesterday, when i was too tired to even think about reporting it

**Comment by PriestOfFerns** [comment]
also i just realized that someone already made a pull request to fix that

**Comment by kuleshov** [comment]
Thank, it should be fixed now
